name: Postman-collection

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run In_Warranty_Flow.postman_collection.json \
          -e UAT.postman_environment.json \
          -r htmlextra
